version: 0.0
os: linux

files:
  - source: ./appspec.yml
    destination: /home/ubuntu
  - source: ./restartTomcat.sh
    destination: /home/ubuntu
  - source: ./EMSP/target/trial-1.0.0-BUILD-SNAPSHOT.war
    destination: /var/lib/tomcat8/webapps
